### ISSUE TITLE
Process files sequentially to decrease memory footprint

### ISSUE THREAD

**Issue by janimo** [simonw/csvs-to-sqlite#21] opened 2017-12-08 10:09 UTC
Unless the data in the input files may need to be processed together (in some of the foreign columns cases maybe?), it would be better to write the sqlite table right after creating the dataframe instead of gathering all dataframes. Right now when importing many files that together contain a lot of data OOM occurs. From what I see freeing Pandas dataframes difficult/impossible 
https://stackoverflow.com/questions/39100971/how-do-i-release-memory-used-by-a-pandas-dataframe

so this may not help either (it did not in a simple test I did)

Right now the only way to import many files is shell scripting around this tool and importing a single file per invocation.

**Comment by simonw** [comment] 2017-12-08 18:27
Definitely want to do this - it's a dupe of #16

**Closed by simonw** 2017-12-08 18:27 UTC
